### ISSUE TITLE
ValueError: Received a NULL pointer.

### ISSUE THREAD

**Issue by HakunaMarthata** [UdK-VPT/Open_eQuarter#73]
Using QGIS 2.18.28 on Windows 10. When executing open eQuarter I get the following error message in the workstep loading information layers. 

```
Ein Fehler trat bei der Ausführung von Python-Code auf: 

ValueError: Received a NULL pointer. 
Traceback (most recent call last):
  File "C:/Users/Martha/.qgis2/python/plugins\mole\view\oeq_dialogs.py", line 513, in 
    self.run_button.clicked.connect(lambda: self.run_automode(mole))
  File "C:/Users/Martha/.qgis2/python/plugins\mole\view\oeq_dialogs.py", line 606, in run_automode
    self.call_next_workstep(mole)
  File "C:/Users/Martha/.qgis2/python/plugins\mole\view\oeq_dialogs.py", line 599, in call_next_workstep
    return mole.standard_workflow.do_next_workstep()
  File "C:/Users/Martha/.qgis2/python/plugins\mole\oeq_workflows.py", line 176, in do_next_workstep
    return self.do_workstep(self.worksteps[self.next_workstep_index()])
  File "C:/Users/Martha/.qgis2/python/plugins\mole\oeq_workflows.py", line 159, in do_workstep
    return self.get_workstep(name).do()
  File "C:/Users/Martha/.qgis2/python/plugins\mole\oeq_workflows.py", line 78, in do
    if self.workstepfunction():
  File "C:/Users/Martha/.qgis2/python/plugins\mole\open_equarter_main.py", line 790, in handle_information_layers_loaded
    i.load()
  File "C:/Users/Martha/.qgis2/python/plugins\mole\extensions\ext.py", line 282, in load
    result = self.load_method(self)
  File "C:/Users/Martha/.qgis2/python/plugins\mole\extensions\acqu_berlin\fbinter_wms_pdens_2012.py", line 7, in load
    self.load_wms()
  File "C:/Users/Martha/.qgis2/python/plugins\mole\extensions\ext.py", line 741, in load_wms
    wms.asGeoTif(geotiff_file)
  File "C:/Users/Martha/.qgis2/python/plugins\mole\qgisinteraction\wms_utils.py", line 79, in asGeoTif
    dst_ds = driver.CreateCopy( filename, src_ds, 0 )
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\osgeo\gdal.py", line 1695, in CreateCopy
    return _gdal.Driver_CreateCopy(self, *args, **kwargs)
ValueError: Received a NULL pointer.


Python-Version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] 
QGIS-Version: 2.18.28 Las Palmas, aa30730ac6 

Python-Pfad:
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python
C:/Users/Martha/.qgis2/python
C:/Users/Martha/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Martha/.qgis2//python
C:\Users\Martha\.qgis2\python\plugins\mole
C:/Users/Martha/Documents/GitHub/WP/QGIS/2
```

The Problem seems to occor in the Files "fbinter_wms_yoc_9293.py" and "fbinter_wms_pdens_2012.py". Im guessing the problem is either in the handling of the WMS data, or the Data from fbinter changed somehow. 

The error has been reproduced on a different windows 10 machine

**Comment by firstdayofjune** [comment]
Hello @HakunaMarthata,

thanks for your feedback. I don't work on the project anymore and looking at the codebase, I must say it has changed quite a lot since the last time I touched it about 5 to 6 years ago.

As for the error, you are right about the origin and it seems as if the wms data can not be fetched correctly, thus the error when writing the file to a GeoTif in the `load_wms` function.

I guess, it would be helpful to know the exact steps you took in order to reproduce the error, but maybe @MaxUdk can step in and help here, since (as mentioned) I am not aware of all the "recent" changes to the code. So it may very well be, he spots the error immediately 🤞
